<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                "name" => "Limpeza Caixa d'agua",
                "bar_code" => "",
                "sale_value" => "450",
                "company_id" => 1,
                "days_notify" => "90",
                "cost_value" => 1,
                "control_quantity" => 1,
                "quantity" => 100,
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ]
        ];
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],
        // [
        //     "name" => "Limpeza Caixa d'agua",
        //     "bar_code" => "",
        //     "sale_value" => "450",
        //     "company_id" => 1,
        //     "days_notify" => "90",
        //     "cost_value" => 1,
        //     "created_at" => Carbon::now(),
        //     "updated_at" => Carbon::now(),
        // ],


        foreach ($data as $row) {
            DB::table('products')->insert($row);
        }
    }
}
